name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        # Environment variable, I want to acess metadata. "${{}}" is an expression.
        run: echo "${{ toJSON(github) }}"