name: Deploy Project
# Have more than one trigger
on: [push, workflow_dispatch]
jobs: 
    # Name of the first job
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code (download from the repository)
              # Pre-defined action
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
    deploy:
        # With needs: they do not run in parallel, in brackets I can make it depended on more than one
        needs: [test]
        runs-on: ubuntu-latest
        steps:
            - name: Get the code (download from the repository)
              # Pre-defined action
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Deploy
              run: echo "Deploying ..."

